### ISSUE TITLE
Explain purpose for separate builds in readme

### ISSUE THREAD

**Issue by panshul007** [bitjson/typescript-starter#10]
I am a newbie switching from ES6 - babel - flow type - config to typescript. The project has been really helpful in wiring all the basic things. 
I was wondering what is the use of `typescript.module.json`?

With the current config, I get a `main` folder and a `module` folder in my `build` folder. Which have almost the same generated code. The only difference being main folder also has an interface file. `filename.d.ts`

Thanks for the help.

**Comment by bitjson** [comment]
Hey @panshul007 – good question! Thanks for opening the issue.

[`tsconfig.module.json`](https://github.com/bitjson/typescript-starter/blob/master/config/tsconfig.module.json) is actually an entirely separate build. If you look at the [build script](https://github.com/bitjson/typescript-starter/blob/a56491f8662e88898e8a314db49984d694f6ff17/package.json#L13), we actually compile your project twice. I should probably add this to the readme. (thanks!) 

Here's a draft explanation, please let me know if it's clear enough:

### Multiple builds (`main` and `module`)

The `src` of typescript-starter is compiled into two separate builds, the `main` and `module` build. The `main` build is [configured to use the CommonJS module system](https://github.com/bitjson/typescript-starter/blob/master/tsconfig.json#L8), while the `module` build [uses the new ES6 module system](https://github.com/bitjson/typescript-starter/blob/master/config/tsconfig.module.json). 

Because Node.js does not yet support the ES6 module system, Node.js projects which depend on typescript-starter will follow the `main` field in [`package.json`](https://github.com/bitjson/typescript-starter/blob/master/package.json). Tools which support the new system (like [Rollup](https://github.com/rollup/rollup)) will follow the `module` field, giving them the ability to tree shake typescript-starter.

Note: by default, the `main` build is the only one exercised by the tests. While both builds are nearly identical, there are real differences in how the two module systems work. For most libraries, this won't be an issue, but for libraries with functionality that varies based on the module system used (generally a bad idea), additional testing is required.

**Comment by panshul007** [comment]
Thanks, the explains a lot.
