### ISSUE TITLE
Import ava

### ISSUE THREAD

**Issue by fredfortier** [bitjson/typescript-starter#108]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I get this build error:
```
src/lib/number.spec.ts:2:10 - error TS2305: Module '".../node_modules/ava/index"' has no exported member 'test'.

2 import { test } from 'ava';
           ~~~~
```
The `ava` module code suggests that `test` should be imported like this: `import test from 'ava';`

**Comment by kyle-john** [comment]
Same problem

**Comment by ShinDarth** [comment]
same problem here, using version `2.3.8`

**Comment by bitjson** [comment]
Thanks for opening/confirming the issue @fredfortier and @kyle-john, and thanks for the PR @ShinDarth! 

This package didn't previously pin the minor version for AVA, and because we were depending on `^1.0.0-beta.6`, this package automatically upgraded to [`1.0.0-beta.7`, which includes some breaking changes](https://github.com/avajs/ava/releases/tag/v1.0.0-beta.7).
