### ISSUE TITLE
Add option to use jest instead of ava

### ISSUE THREAD

**Issue by kristianmandrup** [bitjson/typescript-starter#140]
* **I'm submitting a ...**
[ ] bug report
[ x ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Tried to use this generator and switch from `ava` to `jest` but completely stuck as per this [issue](https://github.com/facebook/jest/pull/6863#issuecomment-441113335).

What gives?

**Comment by bitjson** [comment]
Hey @kristianmandrup, thanks for opening an issue!

I'd love to take a PR to add Jest as an option. I don't really use it outside of React projects myself, so I've not bothered adding it here. 

If you haven't tried AVA, I really recommend it – the API is imported like a normal package, rather than being injected into the global context. I find it usually makes tests cleaner and easier for new contributors to jump right in.

Other than that, you might like this starter project which is also structured in more the "Jest way": https://github.com/alexjoverm/typescript-library-starter

**Comment by kristianmandrup** [comment]
Hey, @bitjson I came from `ava` and `switched` to jest some time ago when I got back into React.
Seems to be the standard in the react community. Never looked back. Jest has huge JS community support, with fancy editor plugins and more. I'll look at the lib you recommended as an alternative.
Cheers.
