### ISSUE TITLE
not create project failed connection

### ISSUE THREAD

**Issue by Paul75** [bitjson/typescript-starter#148]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
do a
>npx typescript-starter

Result : 
npx: installed 364 in 9.92s

  connect ECONNREFUSED 104.16.24.35:443

Thanks

**Comment by bitjson** [comment]
Hey @Paul75 – this seems to be some sort of local connection issue – maybe you're behind some sort of proxy or corporate firewall that won't allow you to download from GitHub?

Since I don't think this is related to any bug in this project, I'm going to close this for now. If you're still having trouble, please feel free to post some additional info, and I'm happy to help.
