### ISSUE TITLE
yarn clean breaks tslint

### ISSUE THREAD

**Issue by semperos** [bitjson/typescript-starter#28]
* **I'm submitting a ...**
[x] bug report

* **Summary**
Do the following:

 1. :white_check_mark: `yarn install`
 2. :white_check_mark: `yarn test`
 3. :white_check_mark: `yarn clean`
 4. :boom: `yarn test`

The `yarn clean` command is deleting files that tslint needs to work correctly. See the output below:

```
$ yarn test
yarn test v0.23.3
$ yarn lint && yarn unit && yarn check-coverage
yarn lint v0.23.3
$ tslint src/**/*.ts
module.js:472
    throw err;
    ^
Error: Cannot find module './test/parse'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dgregoire/tmp/typescript-starter/node_modules/tslint/lib/test.js:28:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

This is due to known issues with how `yarn clean` works.

* **Other information**

If I add a `.yarnclean` file up front that has these contents:

```
!node_modules/tslint/
```

Then running `yarn clean` does not delete the needed files and everything appears to work as expected.

**Comment by bitjson** [comment]
Hey @semperos – thanks for reporting this issue and the fix!

Since `yarn clean` is a pretty uncommon use case, I'd like to avoid adding the `.yarnclean` file to the starter project. Ideally this project should only ship with things that >99% of projects need.

Of course, if anyone else runs into this issue, please make a note on this thread, and we can reconsider. 

I'm going to close this issue for now, but please let me know if it should be reopened.

**Comment by semperos** [comment]
@bitjson Thanks for taking the time to respond!
