### ISSUE TITLE
build-tests.js

### ISSUE THREAD

**Issue by tomdavidson** [bitjson/typescript-starter#30]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Thank you for sharing this! Do you mind explaining the rationale and need for build-tests.js

**Comment by bitjson** [comment]
Hey @tomdavidson – thanks for opening this issue!

I added a note with some additional explanation in: https://github.com/bitjson/typescript-starter/pull/38/commits/f78fa8abc4a89c41645fc1d54a0307e11c974bf6

---

### Testing

By convention, tests in `typescript-starter` are co-located with the files they test. The project is configured to allow tests to be written in Typescript and your library to be imported as if it were being used by another project. (E.g. `import { double, power } from 'typescript-starter'`.) This makes tests both intuitive to write and easy to read as another form of documentation.

Note, tests are compiled and performed on the final builds in the standard Node.js runtime (rather than an alternative like [ts-node](https://github.com/TypeStrong/ts-node)) to ensure tests pass in that environment. If you are using [ts-node in production](https://github.com/TypeStrong/ts-node/issues/104), you can modify this project to skip test compilation.

--- 

Does that answer your question?

**Comment by tomdavidson** [comment]
Thanks @bitjson . It does and I appreciate your response and the project's help getting me started with TS. I did end up deviating quite abit, including on the testing - https://gitlab.com/td7x/s6

**Comment by bitjson** [comment]
Hey @tomdavidson that looks like a fantastic project, thanks for sharing! 

Mind if I link to your project from the readme? https://github.com/bitjson/typescript-starter/commit/f0d349ae70cc15da4aaaf98476094a2bda1e2d92

I've been hoping to add a section of projects using parts from this starter, and yours has some great examples of alternative configurations!

**Comment by tomdavidson** [comment]
not a problem at all and thanks again for helping me get up and running
