### ISSUE TITLE
Use a semi-script-runner to remove yarn dependency from package.json

### ISSUE THREAD

**Issue by Alxandr** [bitjson/typescript-starter#4]
Currently you have stuff like `"unit": "yarn build && nyc ava"` in the package.json, which prevents people from running with npm only. Changing it to `npm run build` would just result in the exact same problem. There are however, multiple libraries made to solve this. I don't remember most of them, because I wrote my own a few months or so ago which you can find here: https://github.com/YoloDev/simple-scripts

However, being written by me, that one is horribly undocumented (see `package.json` for usage), the point is you can create scripts that run a list of other scripts in sequence like a really simple task runner. I would probably go find one of the other ones, but by all means if you like mine you are free to use it.

**Comment by bitjson** [comment]
I was intentionally requiring the use of yarn (because it's fantastic and eliminates a lot of potential headaches), but I don't have a particularly strong opinion about it. Is there a good reason not to use yarn?

**Comment by ihorskyi** [comment]
@bitjson I bet most people still use npm, and don't even have yarn installed on their dev machines. So it is at least a question of supporting all nodejs users or just yarn ones.

**Comment by Alxandr** [comment]
No. It's just a good idea not to force people to use it. Without the `yarn run x && yarn run y` scripts, you enable people to run whatever "thing that can run scripts from package.json" without having what you use installed. As far as I know there are a few of them out there (though afaik yarn and NPM is by far the most used). I just remember this really annoying me on a lot of packages when I switched to yarn, that most packages I worked on used `npm run x && npm run y` requiring npm. This is why I made the `simple-scripts` in the first case.

**Comment by bitjson** [comment]
Thanks for opening this issue @Alxandr – I just made things a little better here: https://github.com/bitjson/typescript-starter/commit/45d7dfad62cd61adc7ad05c2a3614ba8c54dba64

I'd still like to keep yarn as part of the starter (since I think all JS libraries should probably be using it now), and I don't really want to add an extra dependency for a small percentage of users. I updated the examples though. Hopefully that will make them more generally approachable.

Closing this for now, but please let me know if I should reopen.
