### ISSUE TITLE
Why not use a separate test folder?

### ISSUE THREAD

**Issue by Alxandr** [bitjson/typescript-starter#5]
Is there a good reason for having the tests in the same folder?

**Comment by bitjson** [comment]
It's basically a preference thing – I personally prefer it because it encourages better testing practices (keeping tests small, atomic, and easy to maintain). Angular 2 mentions [their reasoning for recommending this setup](https://angular.io/docs/ts/latest/guide/testing.html#!#q-spec-file-location) in their docs.

**Comment by bitjson** [comment]
(Closing this for now, but please let me know if I should reopen.)

**Comment by Alxandr** [comment]
No, I agree. It's a preference thing. I just find it sort of unwieldy. But I'll just change that for myself.
