### ISSUE TITLE
Why not use `ts-node` to run tests?

### ISSUE THREAD

**Issue by tomdavidson** [bitjson/typescript-starter#7]
* **I'm submitting a ...**
[ x ] question about the decisions made in the repository
[ x ] question about how to use this project

* **Summary**

Awesome and thank you for putting this project together. 

Why not use ts-node to run tests (im doing this with mocha and understand ava is quite different) pros/con for tsc first vs using ts-node?

I have an express app that serves up the static files for the client side app. Suggestions on using your starter on both the browser apps and on the nodejs apps?

**Comment by bitjson** [comment]
Glad you like it! And thanks for opening an issue.

> Why not use ts-node to run tests

Generally, I'm not a fan of mingling typescript compiling with the final javascript execution. While it simplifies the mental model a bit, it also makes it a little less clear how things really work.

Ultimately, you want to run tests in exactly the same environment as production code will run. Since some dependants of this library will not be using typescript – and most will not be using `ts-node`, it would likely be concerning that tests are not running in standard Node.js (even if `ts-node` does a perfect job).

> Suggestions on using your starter on both the browser apps and on the nodejs apps?

I'm not sure if I understand the second question – would you mind opening another issue specifically for your second question? (It's best to keep issues separate so they're easier for future users to search and understand.)

**Comment by bitjson** [comment]
I think the first question is answered, so I'm going to go ahead and close this issue – please let me know if I should reopen. Thanks!
