### ISSUE TITLE
Supporting `npm ci` in CI configs

### ISSUE THREAD

**Issue by cspotcode** [bitjson/typescript-starter#75]
* **I'm submitting a ...**
[x] feature request

* **Summary**

Have you thought about supporting the new `npm ci` command in CI configs?

I actually haven't used it much myself, but I think this does the trick:

```bash
if [ -f package-lock.json ] && [ npm ci --help 2>&1 >/dev/null ] ; then npm ci ; else npm install ; fi
```

**Comment by bitjson** [comment]
Sounds great – is there any downside to just replacing usages of `npm install` with `npm ci` in all the CI config? I don’t think think we need a conditional check.

I’d love to take a PR!

**Comment by cspotcode** [comment]
I added the conditional check for when running an older version of `npm`,
since that command was added in the latest release.

**Comment by bitjson** [comment]
Ah, you're right about `npm ci` being a little more complicated right now. I added caching to each of the configurations for now (https://github.com/bitjson/typescript-starter/commit/07f7a3648b53dc82d3aaba58b5f77661130a944d).

I'm hesitant to immediately switch to `npm ci` since we'd have to update npm on each CI environment before using `npm ci`. (Each is at 5.6.0 right now.)

It adds enough to the configuration complexity and build time that I think we're better off just waiting until npm 5.7.0 is available by default on each service before switching over. Leaving open for now. 

---

If you're reading this issue in the future – and CircleCI, Travis CI, and/or Appveyor now ship with at least npm@5.7.0 by default – please send a PR!

**Comment by cspotcode** [comment]
FWIW that conditional one-liner detects if npm supports the `ci` command so
you don't need to update npm; it'll fallback to `install`.

Also, an npm install fallback will always be necessary.  Some projects run
their node tests on multiple versions of node (down to 0.10) so they'll be
running old versions of npm, too.

But I'm fine holding off, too.

**Comment by bitjson** [comment]
> Also, an npm install fallback will always be necessary.

Good point. So once there's a CI environment which supports 5.7.0, we'll still want to use the conditional. 👍

**Comment by bitjson** [comment]
Now that this is the default on any reasonably modern version of `npm` or `yarn`, I think it's safe for us to mark this as "done". 😅 

Thanks again for opening the issue!
